export enum AuditAction {
  // Auth
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
  LOGIN_FAILED = 'LOGIN_FAILED',
  PASSWORD_CHANGED = 'PASSWORD_CHANGED',
  ACCOUNT_LOCKED = 'ACCOUNT_LOCKED',

  // Onboarding
  ONBOARDING_REQUEST_SUBMITTED = 'ONBOARDING_REQUEST_SUBMITTED',
  ONBOARDING_REQUEST_APPROVED = 'ONBOARDING_REQUEST_APPROVED',
  ONBOARDING_REQUEST_REJECTED = 'ONBOARDING_REQUEST_REJECTED',

  // Facility
  FACILITY_CREATED = 'FACILITY_CREATED',
  FACILITY_UPDATED = 'FACILITY_UPDATED',
  FACILITY_SUSPENDED = 'FACILITY_SUSPENDED',

  // User Management
  USER_CREATED = 'USER_CREATED',
  USER_SUSPENDED = 'USER_SUSPENDED',
  USER_DEACTIVATED = 'USER_DEACTIVATED',
  USER_ROLE_CHANGED = 'USER_ROLE_CHANGED',

  // Inventory
  INVENTORY_CREATED = 'INVENTORY_CREATED',
  INVENTORY_UPDATED = 'INVENTORY_UPDATED',
  INVENTORY_ADJUSTED = 'INVENTORY_ADJUSTED',
  INVENTORY_DELETED = 'INVENTORY_DELETED',

  // Resource Requests
  REQUEST_CREATED = 'REQUEST_CREATED',
  REQUEST_ACCEPTED = 'REQUEST_ACCEPTED',
  REQUEST_REJECTED = 'REQUEST_REJECTED',
  REQUEST_COMPLETED = 'REQUEST_COMPLETED',
  REQUEST_CANCELLED = 'REQUEST_CANCELLED',
  REQUEST_DISPATCHED = 'REQUEST_DISPATCHED',
  REQUEST_FAILED = 'REQUEST_FAILED',
}
