export enum NotificationType {
  REQUEST_CREATED = 'REQUEST_CREATED',
  REQUEST_ACKNOWLEDGED = 'REQUEST_ACKNOWLEDGED',
  REQUEST_FULFILLED = 'REQUEST_FULFILLED',
  REQUEST_CANCELED = 'REQUEST_CANCELED',
  REQUEST_EXPIRED = 'REQUEST_EXPIRED',
  BALANCE_LOW = 'BALANCE_LOW',
  BALANCE_TOPUP = 'BALANCE_TOPUP',
}
