export enum StockMovementType {
  RESTOCK = 'RESTOCK',
  CONSUMPTION = 'CONSUMPTION',
  ADJUSTMENT = 'ADJUSTMENT',
  EXPIRED_REMOVAL = 'EXPIRED_REMOVAL',
  DAMAGE = 'DAMAGE',
  TRANSFER_OUT = 'TRANSFER_OUT',
  TRANSFER_IN = 'TRANSFER_IN',
}
