export enum UserRole {
  SUPER_ADMIN = 'SUPER_ADMIN',

  FACILITY_ADMIN = 'FACILITY_ADMIN',

  INVENTORY_MANAGER = 'INVENTORY_MANAGER',

  EMCON_COORDINATOR = 'EMCON_COORDINATOR',

  VIEWER = 'VIEWER',
}
